export const ASYNC = {
    LOAD_MORE : {
        TOTAL_ASSIGN_TO_ME : 'load-more.total-assign-to-me',
        WORK_ON : 'load-more.work-on',
        MORE_VIEWED : 'load-more.viewed',
        ASSIGNED_TO_ME : 'load-more.assigned-to-me',
        STARRED : 'load-more.starred',
        PROJECT_GRID : 'load-more.projec-grid',
        ALL_GROUP:'load-more.all-group',
        ALL_WORKFLOW : 'load-more.all-workflow',
        BACKLOG_PAGE: 'load-more.project.backlog-items',
    },
    FULL_FILLED: {
        TOTAL_ASSIGN_TO_ME : 'full-filled.total-assign-to-me',
        WORK_ON : 'full-filled.work-on',
        MORE_VIEWED : 'full-filled.viewed',
        ASSIGNED_TO_ME : 'full-filled.assigned-to-me',
        STARRED : 'full-filled.starred',
        DELETE_PROJECT: 'full-filled.delete-project',
        PROJECT_GRID : 'full-filled.projec-grid',
        ALL_GROUP:'full-filled.all-group',
        ALL_WORKFLOW : 'full-filled.all-workflow',
        UPDATE_WORKFLOW_LOC: 'full-filled.update-workflow-location',
        NEW_WORKFLOW: 'full-filled.new-workflow',
        NEW_WORKFLOW_ITEM : 'full-filled.new-workflow-item',
        NEW_WORKFLOW_LINK : 'full-filled.new-workflow-link',
        REMOVE_WORKFLOW_ITEM : 'full-filled.remove-workflow-item',
        REMOVE_WORKFLOW_LINK : 'full-filled.remove-workflow-link',
        BACKLOG_PAGE : 'full-filled.project.backlog-items',
        TOP_OF_BACKLOG : 'full-filled.project.top-of-backlog',
        BOTTOM_OF_BACKLOG : 'full-filled.project.bottom-of-backlog',
        DELETE_SPRINT : 'full-filled.project.delete-sprint',
        MOVE_UP_SPRINT : 'full-filled.project.move-up-sprint',
        MOVE_DOWN_SPRINT : 'full-filled.project.move-down-sprint',
        CREATE_SPRINT : 'full-filled.project.create-sprint',
        EDIT_SPRINT : 'full-filled.project.edit-sprint',
        START_SPRINT : 'full-filled.project.start-sprint',
    },
    REQUEST: {
        DELETE_PROJECT : 'request.delete-project',
        CREATE_PROJECT : 'request.create-project',
        CREATE_PROJECT_SUCCESS : 'request.create-project-success',
        CREATE_PROJECT_FAILED : 'request.create-project-failed',
        FAILED : 'request.failed',
        SUCCESS: 'request.success',
        UPDATE_WORKFLOW_LOC: 'request.update-workflow-location',
        CREATE_WORKFLOW : 'request.create-workflow',
        ADD_WORKFLOW_ITEM : 'request.add-workflow-item',
        ADD_WORKFLOW_LINK : 'request.add-workflow-link',
        TOP_OF_BACKLOG : 'request.project.top-of-backlog',
        BOTTOM_OF_BACKLOG : 'request.project.bottom-of-backlog',
        DELETE_SPRINT : 'request.project.delete-sprint',
        MOVE_UP_SPRINT : 'request.project.move-up-sprint',
        MOVE_DOWN_SPRINT : 'request.project.move-down-sprint',
        CREATE_SPRINT : 'request-filled.project.create-sprint',
        EDIT_SPRINT : 'request.project.edit-sprint',
        START_SPRINT : 'request.project.start-sprint',
    }
   
}
export const Router = {
    REDIRECT : "redirect-to",
    CLEAR_REDIRECT_URL : "clear-redirect-url",
}
export const Auth = {
    VALIDATE_TOKEN : "auth-validate-token",
    TOKEN_VALID : "auth-token-valid",
    TOKEN_IN_VALID : "auth-token-in-valid",
    LOGIN : "auth-login",
    LOGIN_SUCCESS : "auth-login-success",
    LOGIN_FAILED : "auth-login-failed",
    SIGN_UP : "auth-sign-up",
    SIGN_UP_SUCCESS : "auth-sign-up-success",
    SIGN_UP_FAILED : "auth-sign-up-failed",
}
export const UI = {
    CHANGE_CONTEXTUAL_NAVIGATION_BAR : "UI-change-contextual-navigation-bar",
}