import {Router as RouterEventTypes, Auth as AuthEventTypes, ASYNC as AsyncEventTypes , UI as UIEventTypes} from '../constants/index'
export const navigateTo = (url) => ({type : RouterEventTypes.REDIRECT, payload: url})
export const clearNavigateTo = () => ({type : RouterEventTypes.CLEAR_REDIRECT_URL, payload: null})
export const validateToken = (token) => ({type : AuthEventTypes.VALIDATE_TOKEN , payload : token})
export const tokenValid = (user) => ({type : AuthEventTypes.TOKEN_VALID , payload : user})
export const tokenInValid = () => ({type : AuthEventTypes.TOKEN_IN_VALID , payload : null})
export const madeRequestFail = (msg) => ({type : AsyncEventTypes.REQUEST.FAILED, payload: msg})
export const madeRequestSuccess = (msg) => ({type : AsyncEventTypes.REQUEST.SUCCESS, payload: msg})
export const login = (userName,password) => ({type : AuthEventTypes.LOGIN, payload: {userName , password}})
export const loginSuccess = (token) => ({type : AuthEventTypes.LOGIN_SUCCESS, payload : token})
export const loginFailed = () => ({type : AuthEventTypes.LOGIN_FAILED, payload: "Your credentials are in-correct!"})
export const signUp = (userName,password,confirmPassword) => ({type : AuthEventTypes.SIGN_UP, payload: {userName , password, confirmPassword}})
export const signUpSuccess = () => ({type : AuthEventTypes.SIGN_UP_SUCCESS})
export const signUpFailed = (message) => ({type : AuthEventTypes.SIGN_UP_FAILED, payload: message == null ? 'Sign-up error!' : message})
export const pageContextualNavigation = (pageName, data) => ({type : UIEventTypes.CHANGE_CONTEXTUAL_NAVIGATION_BAR , payload : {pageName,data}})
export const fetchAboutMe = () => ({type: AsyncEventTypes.REQUEST.ABOUT_ME})
export const fullFilledAboutMe = (user) => ({type: AsyncEventTypes.FULL_FILLED.ABOUT_ME, payload: user})