import {ASYNC as AsyncEventTypes} from '../constants/index'
export const deleteProject = (id) => ({type : AsyncEventTypes.REQUEST.DELETE_PROJECT, payload: id})
export const createProject = (payload) => ({type : AsyncEventTypes.REQUEST.CREATE_PROJECT , payload})
export const createProjectSuccess = (projectCreated) => ({type : AsyncEventTypes.REQUEST.CREATE_PROJECT_SUCCESS , payload : projectCreated})
export const createProjectFailed = (msg) => ({type : AsyncEventTypes.REQUEST.CREATE_PROJECT_FAILED , payload : msg})
export const fetchProjectGrid = () => ({type:AsyncEventTypes.LOAD_MORE.PROJECT_GRID})
export const fullFilledProjectGrid = (data) => ({type: AsyncEventTypes.FULL_FILLED.PROJECT_GRID, payload: data})
export const fullFilledDeleteProject = (id) => ({type: AsyncEventTypes.FULL_FILLED.DELETE_PROJECT, payload: id})

export const fetchAllWorkFlow = (projectId) => ({type: AsyncEventTypes.LOAD_MORE.ALL_WORKFLOW, payload: projectId})
export const fullFilledAllWorkFlow = (data) => ({type: AsyncEventTypes.FULL_FILLED.ALL_WORKFLOW, payload: data})
export const updateWorkFlowLocation = (data) => ({type: AsyncEventTypes.REQUEST.UPDATE_WORKFLOW_LOC, payload: data})
export const fullFilledUpdateWorkFlowLocation = (data) => ({type: AsyncEventTypes.FULL_FILLED.UPDATE_WORKFLOW_LOC, payload: data})
export const createWorkFlow = (data) => ({type: AsyncEventTypes.REQUEST.CREATE_WORKFLOW, payload: data})
export const fullFilledNewWorkFlow = (data) => ({type: AsyncEventTypes.FULL_FILLED.NEW_WORKFLOW, payload: data})
export const addWorkFlowItem = (data) => ({type: AsyncEventTypes.REQUEST.ADD_WORKFLOW_ITEM, payload: data})
export const fullFilledNewWorkFlowItem = (data) => ({type: AsyncEventTypes.FULL_FILLED.NEW_WORKFLOW_ITEM, payload: data})
export const addWorkFlowLink = (data) => ({type: AsyncEventTypes.REQUEST.ADD_WORKFLOW_LINK, payload: data})
export const fullFilledNewWorkFlowLink = (data) => ({type: AsyncEventTypes.FULL_FILLED.NEW_WORKFLOW_LINK, payload: data})

export const fetchBacklogPage = (projectId) => ({type: AsyncEventTypes.LOAD_MORE.BACKLOG_PAGE , payload: projectId})
export const fullFilledBacklogPage = (data) => ({type: AsyncEventTypes.FULL_FILLED.BACKLOG_PAGE , payload: data})
